// ─────────────────────────────────────────────────────────────────────────────
// codegen.ts — Bundle assembly
//
// Assembles the transformed modules into a single self-contained IIFE bundle
// with a tripack runtime.  The runtime pattern is intentionally similar to
// webpack's output so the concept is easy to map between the two.
//
// Bundle structure:
//
//   /****** tripack runtime ******/
//   (function(modules) {
//
//     // Module cache
//     var __module_cache__ = {};
//
//     // The require function
//     function __require(moduleId) { ... }
//
//     // Mark this bundle as ESM-compatible
//     __require.esm = true;
//
//     // Execute entry module
//     return __require("<entry-path>");
//
//   })({
//     "<path>": function(module, exports, __require) {
//       // transformed module code
//     },
//     ...
//   });
// ─────────────────────────────────────────────────────────────────────────────

import type { Module } from './types.js';

const BANNER = `\
/*!
 * Bundle generated by tripack — https://github.com/otabekoff/tripack
 * Modules: {MODULE_COUNT} | Built: {DATE}
 */`;

/**
 * Generate the final bundle string from a list of transformed modules.
 *
 * @param modules   All modules in dependency order (leaves first, entry last)
 * @param entry     The entry module
 */
export function generateBundle(modules: Module[], entry: Module): string {
  const runtimeIdMap = createRuntimeIdMap(modules);

    const date = new Date().toISOString();
    const banner = BANNER
        .replace('{MODULE_COUNT}', String(modules.length))
        .replace('{DATE}', date);

    const moduleDefinitions = modules
    .map(mod => formatModuleDefinition(mod, runtimeIdMap))
        .join(',\n\n');

  const runtime = buildRuntime(runtimeIdMap.get(entry.id) ?? entry.id);

    return [
        banner,
        '',
        `;(function(modules) {`,
        '',
        indent(runtime, 2),
        '',
        `})({`,
        '',
        moduleDefinitions,
        '',
        `});`,
        '', // trailing newline
    ].join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Runtime
// ─────────────────────────────────────────────────────────────────────────────

function buildRuntime(entryId: string): string {
    return `\
/****** tripack runtime ******/

/** Installed (cached) modules */
var __module_cache__ = {};

/** Native require fallback for Node.js builtins/external modules */
var __native_require__ =
  typeof require === 'function'
    ? require
    : (typeof module !== 'undefined' && module && typeof module.require === 'function'
        ? module.require.bind(module)
        : null);

/**
 * Require a module by its internal runtime id.
 * Implements the CommonJS module wrapper pattern.
 */
function __require(moduleId) {
  // Return from cache if already executed
  var cachedModule = __module_cache__[moduleId];
  if (cachedModule !== undefined) {
    return cachedModule.exports;
  }

  // Delegate unknown ids to the host runtime (e.g. node:path)
  if (!Object.prototype.hasOwnProperty.call(modules, moduleId)) {
    if (__native_require__) {
      return __native_require__(moduleId);
    }
    throw new Error('Cannot resolve external module: ' + moduleId);
  }

  // Create a new module object and store it in the cache BEFORE execution.
  // This is the key trick that breaks circular dependency infinite loops.
  var module = (__module_cache__[moduleId] = {
    id: moduleId,
    loaded: false,
    exports: {},
  });

  // Execute the module factory
  modules[moduleId].call(
    module.exports, // \`this\`
    module,         // \`module\`
    module.exports, // \`exports\`
    __require,      // \`require\`
  );

  module.loaded = true;
  return module.exports;
}

/** Allows interop with code that checks for ESM bundles */
__require.esm = true;

/****** Execute entry module ******/
return __require(${JSON.stringify(entryId)});`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Module definition formatter
// ─────────────────────────────────────────────────────────────────────────────

function formatModuleDefinition(mod: Module, runtimeIdMap: Map<string, string>): string {
  const runtimeId = runtimeIdMap.get(mod.id) ?? mod.id;
  const transformed = remapDependencyIds(mod.transformed, mod.dependencyMap, runtimeIdMap);

  const header = `  ${JSON.stringify(runtimeId)}: function(module, exports, __require) {`;
  const body = indent(transformed.trim(), 4);
    const footer = `  }`;

    return [header, body, footer].join('\n');
}

function createRuntimeIdMap(modules: Module[]): Map<string, string> {
  const map = new Map<string, string>();
  modules.forEach((mod, index) => {
    map.set(mod.id, `m${index}`);
  });
  return map;
}

function remapDependencyIds(
  transformedCode: string,
  dependencyMap: Record<string, string>,
  runtimeIdMap: Map<string, string>,
): string {
  let code = transformedCode;
  const dependencyIds = new Set(Object.values(dependencyMap));

  for (const depId of dependencyIds) {
    const runtimeDepId = runtimeIdMap.get(depId);
    if (!runtimeDepId) continue;

    const from = `__require(${JSON.stringify(depId)})`;
    const to = `__require(${JSON.stringify(runtimeDepId)})`;
    code = code.split(from).join(to);
  }

  return code;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function indent(text: string, spaces: number): string {
    const pad = ' '.repeat(spaces);
    return text
        .split('\n')
        .map(line => (line.trim() === '' ? '' : pad + line))
        .join('\n');
}